export const siteConfig = {
  name: "DistroAgents",
  description:
    "Purpose-built AI agents for wholesale distributors. Automate sales, orders, collections, pricing, and compliance.",
  url: "https://distroagents.com",
  email: "hello@distroagents.com",
  phone: "(888) 555-0199",
};

export const navLinks = [
  {
    label: "Use Cases",
    href: "/use-cases",
    children: [
      {
        label: "Sales",
        href: "/use-cases/sales-customer-acquisition",
        description: "Prospecting, quoting, lead qualification",
      },
      {
        label: "Order Management",
        href: "/use-cases/order-management",
        description: "Order intake, validation, status, reordering",
      },
      {
        label: "Pricing & Margins",
        href: "/use-cases/pricing-intelligence",
        description: "Dynamic pricing, margin protection",
      },
      {
        label: "Operations & Logistics",
        href: "/use-cases/operations-logistics",
        description: "Routing, inventory, warehouse, delivery",
      },
      {
        label: "Customer Service",
        href: "/use-cases/customer-service",
        description: "Inquiries, complaints, returns, support",
      },
      {
        label: "Finance",
        href: "/use-cases/finance-ar",
        description: "Collections, credit, invoicing",
      },
      {
        label: "Compliance",
        href: "/use-cases/compliance",
        description: "Food safety, traceability, recalls",
      },
    ],
  },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const useCaseCategories = [
  {
    slug: "sales-customer-acquisition",
    title: "Sales",
    shortTitle: "Sales",
    description:
      "Turn your sales team into a revenue machine by automating prospecting, quoting, and follow-up.",
    tagline: "Turn Your Sales Team into a Revenue Machine",
    agentCount: 6,
    color: "blue",
    icon: "chart-bar",
    keyOutcomes: [
      "3-5x increase in outbound touches",
      "80% faster quoting",
      "15-25% dormant account reactivation",
    ],
    agents: [
      {
        name: "Outbound Prospecting Agent",
        what: "Autonomously identifies, researches, and initiates contact with potential customers in your target market.",
        how: "Ingests your ideal customer profile, scans business databases, researches prospects, crafts personalized outreach, sequences follow-ups, and books meetings on rep calendars.",
        features: [
          "Multi-channel outreach (email, LinkedIn, SMS)",
          "Personalization at scale",
          "A/B testing of messaging",
          "Territory and account assignment rules",
          "CRM integration",
          "Do-not-contact list compliance",
        ],
        painPoints: [
          "Reps no longer spend hours researching prospects",
          "Consistent outreach volume",
          "No leads slip through the cracks",
        ],
        metrics: [
          "3-5x increase in outbound touches per rep",
          "40% reduction in time-to-first-contact",
        ],
      },
      {
        name: "Lead Qualification Agent",
        what: "Scores, qualifies, and routes inbound leads based on fit and buying intent.",
        how: "Receives leads from all channels, asks qualifying questions, scores leads, routes hot leads to reps, nurtures warm leads, disqualifies poor-fit leads.",
        features: [
          "Custom scoring models",
          "Real-time routing to available reps",
          "Integration with web forms, chat, phone",
          "Lead source attribution",
          "Automated nurture sequences",
          "Handoff summaries for reps",
        ],
        painPoints: [
          "Stop wasting time on unqualified leads",
          "Hot leads get immediate response",
          "No leads lost in handoff",
        ],
        metrics: [
          "50% reduction in rep time on unqualified leads",
          "2x improvement in lead-to-opportunity conversion",
        ],
      },
      {
        name: "Quote Generation Agent",
        what: "Instantly generates accurate, margin-protected quotes based on customer requirements.",
        how: "Pulls current pricing, checks inventory, applies customer-specific tiers, calculates margin, generates professional quotes, tracks status and follow-ups.",
        features: [
          "Real-time inventory and pricing checks",
          "Margin guardrails",
          "Volume discount calculation",
          "E-signature integration",
          "Automated follow-up on pending quotes",
          "Quote versioning and comparison",
        ],
        painPoints: [
          "Quotes in minutes, not hours",
          "Consistent pricing across reps",
          "No margin giveaways",
        ],
        metrics: [
          "80% reduction in quote turnaround time",
          "15% improvement in quote-to-close ratio",
          "1-2% margin improvement",
        ],
      },
      {
        name: "Account Reactivation Agent",
        what: "Systematically re-engages dormant customers to win back their business.",
        how: "Identifies declining accounts, researches reasons, crafts win-back campaigns, offers incentives, schedules calls for reps.",
        features: [
          "Configurable dormancy triggers",
          "Churn risk scoring",
          "Personalized messaging",
          "Incentive recommendation engine",
          "Multi-touch campaigns",
          "Win-back revenue attribution",
        ],
        painPoints: [
          "Dormant accounts no longer forgotten",
          "Systematic approach to win-back",
          "Recover revenue from existing customers",
        ],
        metrics: [
          "15-25% reactivation rate on dormant accounts",
          "Average 6-month revenue recovery per reactivation",
        ],
      },
      {
        name: "New Account Onboarding Agent",
        what: "Streamlines setup from signed deal to first order.",
        how: "Sends welcome package, collects information, runs credit check, creates ERP account, schedules onboarding, monitors for first order.",
        features: [
          "Digital credit application with auto-decisioning",
          "Document collection and verification",
          "ERP account creation automation",
          "Product recommendation by business type",
          "First-order incentive automation",
          "Delivery preference capture",
        ],
        painPoints: [
          "New accounts don't languish waiting",
          "Consistent onboarding experience",
          "Faster time-to-first-order",
        ],
        metrics: [
          "60% reduction in account setup time",
          "30% faster time-to-first-order",
        ],
      },
      {
        name: "Sales Intelligence Agent",
        what: "Provides real-time intelligence on accounts, competitors, and market conditions.",
        how: "Monitors order patterns, tracks competitor activity, alerts to upsell opportunities, provides pre-call briefs, aggregates market news.",
        features: [
          "Account health scoring",
          "Competitor tracking and alerts",
          "Purchase pattern analysis",
          "Pre-call intelligence briefs",
          "Cross-sell/upsell recommendations",
          "Share-of-wallet analysis",
        ],
        painPoints: [
          "Reps walk into calls prepared",
          "Proactive identification of at-risk accounts",
          "Systematic upsell/cross-sell",
        ],
        metrics: [
          "20% increase in average order value",
          "Early warning on 80%+ at-risk accounts",
        ],
      },
    ],
    challenge: [
      {
        problem: "Sales reps spend 60%+ of time on admin tasks",
        impact: "Less time in front of customers",
      },
      {
        problem: "Manual prospecting is slow and inconsistent",
        impact: "Pipeline gaps, missed opportunities",
      },
      {
        problem: "Quote turnaround takes hours or days",
        impact: "Lost deals to faster competitors",
      },
      {
        problem: "No systematic follow-up on leads",
        impact: "Leads go cold, money left on table",
      },
      {
        problem: "Dormant accounts forgotten",
        impact: "Existing customers defect to competitors",
      },
      {
        problem: "Inconsistent messaging across reps",
        impact: "Brand dilution, pricing confusion",
      },
    ],
    integrations: {
      crm: ["Salesforce", "HubSpot", "Zoho CRM", "Microsoft Dynamics 365 Sales", "Pipedrive"],
      erp: ["Connection to pricing engine", "Inventory availability checks", "Customer master data sync"],
      communication: ["Email (Gmail, Outlook)", "LinkedIn Sales Navigator", "Phone/SMS (Twilio)", "Calendar (Google, Outlook)"],
    },
    recommendedFirst: "Quote Generation Agent or Lead Qualification Agent",
    recommendedWhy:
      "Immediate time savings for sales team, measurable improvement in speed-to-quote or speed-to-lead.",
    deploymentTime: "2-3 weeks",
    roi: [
      { metric: "Quotes per rep per day", before: "5", after: "20", impact: "4x volume" },
      { metric: "Quote turnaround time", before: "4 hours", after: "15 minutes", impact: "94% faster" },
      { metric: "Lead response time", before: "24 hours", after: "5 minutes", impact: "Competitive advantage" },
      { metric: "Dormant account outreach", before: "Ad hoc", after: "Systematic", impact: "Revenue recovery" },
      { metric: "Rep selling time", before: "40%", after: "70%", impact: "75% more selling" },
    ],
    faq: [
      {
        q: "Will this replace my sales reps?",
        a: "No. These agents handle the tasks that prevent your reps from selling. Your reps become more productive, not redundant.",
      },
      {
        q: "Can I control what the agents say?",
        a: "Yes. You approve messaging templates and set guardrails. The agent personalizes within your approved framework.",
      },
      {
        q: "What if a lead wants to talk to a human?",
        a: "Agents are trained to recognize this and hand off immediately. Human escalation is always available.",
      },
      {
        q: "How does it handle complex quotes?",
        a: "Configurable complexity thresholds. Simple quotes auto-generate; complex quotes get flagged for rep review.",
      },
    ],
  },
  {
    slug: "order-management",
    title: "Order Management",
    shortTitle: "Orders",
    description:
      "Capture orders from any channel, validate automatically, and keep customers informed.",
    tagline: "Every Order, Handled Perfectly",
    agentCount: 6,
    color: "green",
    icon: "clipboard-list",
    keyOutcomes: [
      "70% order automation",
      "35% reduction in errors",
      "24/7 order capture",
    ],
    agents: [
      {
        name: "Voice Order Agent",
        what: "Takes orders via phone using natural conversation, just like your best order desk rep.",
        how: "Answers calls, identifies customer, takes order through conversation, handles lookups and substitutions, confirms details, sends confirmation.",
        features: [
          "Natural language understanding",
          "Real-time inventory checks",
          "Customer-specific pricing",
          "Substitution suggestions",
          "Multilingual support (English, Spanish)",
          "Seamless human handoff",
        ],
        painPoints: [
          "24/7 order taking without staffing costs",
          "Handle volume spikes without hold times",
          "Consistent order accuracy",
        ],
        metrics: [
          "70% of routine orders handled without human",
          "40% reduction in order desk staffing",
          "99.2% order accuracy rate",
        ],
      },
      {
        name: "Text/SMS Order Agent",
        what: "Processes orders received via text message or WhatsApp.",
        how: "Parses text messages, confirms interpretation, processes order on customer confirmation, sends order number and ETA.",
        features: [
          "Natural language parsing",
          "Typo and shorthand correction",
          "Photo order support",
          "Order confirmation workflow",
          "Payment link integration",
          "Conversation history for context",
        ],
        painPoints: [
          "Capture orders from text-happy customers",
          "No app download required",
          "Async ordering fits customer schedules",
        ],
        metrics: [
          "45% of customers prefer text ordering once available",
          "90% order completion rate via text",
        ],
      },
      {
        name: "Email Order Agent",
        what: "Extracts and processes orders from emails, including attachments.",
        how: "Monitors order inbox, parses emails and attachments, extracts products and quantities, maps to SKUs, submits order and sends confirmation.",
        features: [
          "Attachment parsing (PDF, Excel, Word, images)",
          "Item number mapping",
          "Free-text item description matching",
          "Ambiguity detection and clarification",
          "PO number extraction",
          "Integration with customer catalogs",
        ],
        painPoints: [
          "No more manual email order re-entry",
          "Process email orders in minutes",
          "Handle messy, inconsistent formats",
        ],
        metrics: [
          "85% of email orders processed without human touch",
          "95% reduction in email order processing time",
        ],
      },
      {
        name: "Order Validation Agent",
        what: "Checks every order for errors, anomalies, and issues before fulfillment.",
        how: "Scans every incoming order, validates against business rules and historical patterns, flags exceptions, auto-approves clean orders.",
        features: [
          "Pattern-based anomaly detection",
          "Customer-specific validation rules",
          "Credit limit checking",
          "Duplicate order detection",
          "Min/max order enforcement",
          "Approval workflows for exceptions",
        ],
        painPoints: [
          "Catch errors before they become expensive",
          "Reduce credits and returns",
          "Prevent fraud and unusual orders",
        ],
        metrics: [
          "92% of order errors caught before fulfillment",
          "35% reduction in credits and returns",
        ],
      },
      {
        name: "Order Status Agent",
        what: "Provides real-time order status to customers via any channel.",
        how: "Identifies customer and order, retrieves real-time status from WMS/TMS/ERP, provides specific information, proactively notifies of delays.",
        features: [
          "Real-time tracking integration",
          "Proactive delay notifications",
          "ETA predictions based on route data",
          "Delivery confirmation with POD",
          "Issue escalation to customer service",
          "Preferred channel per customer",
        ],
        painPoints: [
          "Eliminate 'where's my order' calls",
          "Customers get instant answers 24/7",
          "Proactive communication builds trust",
        ],
        metrics: [
          "80% reduction in order status inquiries",
          "Customer satisfaction improvement",
        ],
      },
      {
        name: "Predictive Reorder Agent",
        what: "Suggests reorders based on customer purchase patterns and predicts when customers will need to reorder.",
        how: "Analyzes order history, identifies patterns, predicts next order timing, sends proactive reminders, pre-builds suggested orders.",
        features: [
          "ML-based purchase pattern analysis",
          "Seasonality and trend detection",
          "Pre-built order suggestions",
          "One-click approval workflow",
          "A/B testing of reminder timing",
          "Integration with inventory levels",
        ],
        painPoints: [
          "Never miss a reorder opportunity",
          "Make ordering effortless",
          "Increase order frequency and lifetime value",
        ],
        metrics: [
          "25% increase in order frequency",
          "15% increase in average order value",
        ],
      },
    ],
    challenge: [
      { problem: "Orders arrive via phone, text, email, fax, portal", impact: "Manual re-entry, errors, delays" },
      { problem: "Staff tied up on phones taking orders", impact: "Can't handle volume spikes, overtime costs" },
      { problem: "Order errors cause credits and returns", impact: "Margin erosion, customer frustration" },
      { problem: "Customers can't get quick order status", impact: "High call volume, poor experience" },
      { problem: "Reorders depend on customer memory", impact: "Missed sales, inconsistent ordering" },
      { problem: "After-hours orders wait until morning", impact: "Lost business to 24/7 competitors" },
    ],
    integrations: {
      orderSources: ["Phone systems (Twilio, RingCentral)", "SMS/WhatsApp", "Email (Gmail, Outlook)", "EDI (850 Purchase Orders)", "eCommerce platforms"],
      backend: ["ERP (order entry, pricing)", "WMS (inventory, order status)", "TMS (delivery tracking)"],
      communication: ["Email confirmations", "SMS confirmations", "Customer portals"],
    },
    recommendedFirst: "Voice Order Agent or Order Status Agent",
    recommendedWhy: "Immediate labor savings on highest-volume channel or quick win reducing inbound calls.",
    deploymentTime: "2-4 weeks",
    roi: [
      { metric: "Orders requiring manual entry", before: "100%", after: "30%", impact: "70% automation" },
      { metric: "Order desk FTEs needed", before: "5", after: "2", impact: "$150K+ savings" },
      { metric: "Order errors", before: "3%", after: "0.5%", impact: "83% reduction" },
      { metric: "After-hours orders captured", before: "0%", after: "100%", impact: "New revenue" },
      { metric: "Order status calls per day", before: "50", after: "10", impact: "80% reduction" },
    ],
    faq: [
      { q: "Can the voice agent handle complex orders?", a: "Yes, for most orders. For highly complex situations, it seamlessly transfers to a human." },
      { q: "What about customers who don't want to talk to an AI?", a: "They can always press 0 to reach a human. Most customers prefer the speed once they try it." },
      { q: "How does it handle accents?", a: "Our voice recognition is trained on diverse accents and handles background noise. Accuracy exceeds 95%." },
      { q: "What if inventory changes between order and fulfillment?", a: "The Validation Agent checks real-time inventory. The Status Agent proactively notifies with substitution options." },
    ],
  },
  {
    slug: "pricing-intelligence",
    title: "Pricing & Margins",
    shortTitle: "Pricing",
    description:
      "Protect every point of margin with intelligent pricing and reconciliation.",
    tagline: "Protect Every Point of Margin",
    agentCount: 5,
    color: "purple",
    icon: "currency-dollar",
    keyOutcomes: [
      "1-2% margin improvement",
      "2-5% AP cost recovery",
      "Zero negative-margin transactions",
    ],
    agents: [
      {
        name: "Dynamic Pricing Agent",
        what: "Continuously optimizes pricing based on costs, inventory, competition, and demand signals.",
        how: "Monitors supplier costs, tracks inventory velocity, ingests competitive intel, analyzes demand patterns, calculates optimal prices, recommends or auto-updates.",
        features: ["Cost-plus pricing automation", "Market-based pricing for commodities", "Inventory-based pricing", "Demand elasticity modeling", "Price change simulation", "Automated updates within guardrails"],
        painPoints: ["React to cost changes in hours, not weeks", "Optimize for inventory velocity", "Never sell below margin floor"],
        metrics: ["1-2% overall margin improvement", "90% reduction in cost propagation time", "Zero negative-margin transactions"],
      },
      {
        name: "Margin Protection Agent",
        what: "Enforces margin guardrails across all transactions and prevents margin giveaways.",
        how: "Monitors every quote, order, transaction in real-time, calculates actual margin, flags or blocks below-threshold transactions, identifies erosion patterns.",
        features: ["Real-time margin calculation", "Configurable margin floors", "Rep-level margin tracking", "Approval workflows for exceptions", "Cost refresh integration", "Commission system integration"],
        painPoints: ["Stop reps from giving away margin", "Pricing reflects current costs", "Full margin visibility"],
        metrics: ["15-25% reduction in below-threshold approvals", "$200K+ annual margin recovery", "Full visibility into margin drivers"],
      },
      {
        name: "Contract Pricing Agent",
        what: "Manages customer contracts, ensures correct pricing, and tracks contract performance.",
        how: "Stores contract terms, auto-applies correct pricing, tracks volumes, alerts on expiration, identifies under-performing customers, generates renewal recommendations.",
        features: ["Contract repository", "Automatic price application", "Volume commitment tracking", "Expiration alerting", "Renewal pricing recommendations", "Contract audit trail"],
        painPoints: ["Never apply wrong contract price", "Know which customers meet commitments", "Proactive contract renewal"],
        metrics: ["100% contract pricing accuracy", "95% renewal rate", "10% volume increase from tracking"],
      },
      {
        name: "Invoice Reconciliation Agent",
        what: "Reconciles vendor invoices against POs and receipts, catching overcharges.",
        how: "Ingests vendor invoices, performs 3-way match (PO, Receipt, Invoice), flags discrepancies, auto-approves within tolerance, tracks rebates and allowances.",
        features: ["PDF/image invoice OCR", "EDI 810 processing", "3-way match automation", "Tolerance-based auto-approval", "Rebate and allowance tracking", "Vendor performance scoring"],
        painPoints: ["Stop paying more than you should", "Catch every discrepancy", "Claim all rebates owed"],
        metrics: ["2-5% cost recovery on AP spend", "85% invoices auto-matched", "99% rebate capture rate"],
      },
      {
        name: "Competitive Intelligence Agent",
        what: "Monitors competitor pricing, positioning, and market activity.",
        how: "Tracks competitor published pricing, analyzes lost deals, monitors news, surveys market pricing, identifies positioning gaps, recommends adjustments.",
        features: ["Competitor price database", "Win/loss pricing analysis", "Market price indexing", "Competitor news monitoring", "Rep intelligence capture", "Price positioning reports"],
        painPoints: ["Know where you stand vs. competition", "Identify pricing opportunities", "Data-driven pricing decisions"],
        metrics: ["Comprehensive competitive visibility", "Faster response to competitive moves", "Improved win rates"],
      },
    ],
    challenge: [
      { problem: "Sales reps discount too aggressively", impact: "Margin erosion of 1-3%" },
      { problem: "Pricing inconsistent across reps and channels", impact: "Customer confusion, cherry-picking" },
      { problem: "Cost changes not propagated quickly", impact: "Selling at negative margin" },
      { problem: "No real-time margin visibility", impact: "Flying blind" },
      { problem: "Contract pricing not enforced", impact: "Revenue leakage" },
      { problem: "Competitive pricing unknown or outdated", impact: "Losing deals or leaving money on table" },
    ],
    integrations: {
      erp: ["Price file management", "Cost updates and landed cost", "Customer tier management", "Transaction data"],
      procurement: ["Purchase orders", "Receiving documents", "Vendor invoices"],
      sales: ["Quotes and proposals", "Won/lost deal data", "Contract management"],
    },
    recommendedFirst: "Invoice Reconciliation Agent or Margin Protection Agent",
    recommendedWhy: "Immediate cost recovery or stops margin bleeding on every transaction.",
    deploymentTime: "3-4 weeks",
    performancePricing: true,
    roi: [
      { metric: "AP cost recovery", before: "0%", after: "2-5%", impact: "$400K-$1M (on $50M)" },
      { metric: "Margin improvement", before: "Baseline", after: "+1-2%", impact: "$500K-$1M" },
      { metric: "Rebate capture", before: "70%", after: "99%", impact: "$250K-$500K" },
      { metric: "Below-threshold deals", before: "Frequent", after: "Rare", impact: "$50-100K savings" },
    ],
    faq: [
      { q: "How does this work with my current ERP pricing?", a: "We integrate with your ERP's price file. We can recommend changes or auto-update within defined parameters." },
      { q: "What if I don't want fully automated pricing?", a: "You control the automation level. Start with recommendations and approvals, then increase automation." },
      { q: "How do you handle customer-specific pricing?", a: "Fully supported. We respect customer tiers, contract pricing, and individual agreements." },
      { q: "What about catch-weight items?", a: "Yes, we handle catch-weight pricing and margin calculation correctly." },
    ],
  },
  {
    slug: "operations-logistics",
    title: "Operations & Logistics",
    shortTitle: "Operations",
    description:
      "Optimize routing, predict demand, manage inventory, and coordinate logistics.",
    tagline: "Run a Tighter Ship, Automatically",
    agentCount: 7,
    color: "orange",
    icon: "truck",
    keyOutcomes: [
      "15-25% route cost reduction",
      "40-60% shrink reduction",
      "20-30% productivity improvement",
    ],
    agents: [
      {
        name: "Route Optimization Agent",
        what: "Automatically plans and optimizes delivery routes based on orders, constraints, and real-time conditions.",
        how: "Ingests orders, considers vehicle capacity, delivery windows, traffic, and driver schedules to generate optimal routes.",
        features: ["Multi-stop route optimization", "Real-time traffic integration", "Dynamic re-routing", "Customer ETA notifications", "Fuel cost optimization", "Multi-vehicle load balancing"],
        painPoints: ["Reduce miles and fuel costs", "Improve on-time delivery", "Handle same-day changes"],
        metrics: ["15-25% reduction in route miles", "20% improvement in on-time delivery", "30% reduction in planning time"],
      },
      {
        name: "Inventory Forecasting Agent",
        what: "Predicts future demand by SKU and recommends optimal inventory levels.",
        how: "Analyzes historical sales, incorporates weather/events/seasonality, generates forecasts, recommends reorder points.",
        features: ["ML-based demand forecasting", "Weather-based adjustments", "Promotion impact modeling", "Safety stock optimization", "Forecast accuracy tracking", "Integration with purchasing"],
        painPoints: ["Reduce stockouts on key items", "Lower carrying costs", "Better cash flow"],
        metrics: ["30-50% reduction in stockouts", "15-20% reduction in carrying costs", "85%+ forecast accuracy"],
      },
      {
        name: "Expiration & FIFO Agent",
        what: "Tracks perishable inventory, ensures FIFO compliance, and alerts to expiration risks.",
        how: "Monitors inventory by lot with expiration dates, calculates sell-through velocity, identifies at-risk inventory, recommends actions.",
        features: ["Lot/batch tracking with expiration", "Shelf life velocity calculations", "FIFO pick enforcement", "At-risk inventory alerts", "Markdown recommendations", "Shrink reporting"],
        painPoints: ["Reduce spoilage and waste", "Ensure FIFO compliance", "Proactive decisions, not reactive write-offs"],
        metrics: ["40-60% reduction in perishable shrink", "100% FIFO compliance", "90%+ at-risk inventory identified"],
      },
      {
        name: "Warehouse Task Agent",
        what: "Optimizes warehouse operations by prioritizing and assigning tasks to maximize throughput.",
        how: "Receives all tasks, prioritizes by cutoff times and efficiency, assigns to workers via mobile, tracks completion and productivity.",
        features: ["Real-time task prioritization", "Worker assignment optimization", "Batch picking logic", "Productivity tracking", "SLA risk alerts", "Integration with WMS/RF devices"],
        painPoints: ["Maximize picks per hour", "Priority orders ship on time", "Balance workload"],
        metrics: ["20-30% improvement in picks per hour", "95%+ on-time completion", "25% reduction in overtime"],
      },
      {
        name: "Delivery Tracking Agent",
        what: "Provides real-time visibility into every delivery and manages exceptions proactively.",
        how: "Tracks driver location and progress, updates ETAs dynamically, notifies customers, detects exceptions, captures proof of delivery.",
        features: ["Real-time GPS tracking", "Dynamic ETA calculation", "Customer notification (SMS, email)", "Exception detection", "Proof of delivery capture", "Historical delivery performance"],
        painPoints: ["Know where every driver is", "Proactively manage delays", "Reduce delivery inquiries"],
        metrics: ["100% real-time delivery visibility", "70% reduction in delivery inquiries", "40% faster exception resolution"],
      },
      {
        name: "Receiving & QC Agent",
        what: "Streamlines inbound receiving by automating verification, quality checks, and put-away decisions.",
        how: "Retrieves expected deliveries, guides staff through verification, compares received to expected, routes quality issues, determines put-away location.",
        features: ["PO/ASN matching", "Guided receiving workflows", "Quality inspection checklists", "Photo documentation", "Discrepancy flagging", "Vendor scorecard updates"],
        painPoints: ["Faster, more accurate receiving", "Consistent quality checks", "Immediate inventory visibility"],
        metrics: ["40% reduction in receiving time", "95% receiving accuracy", "50% reduction in put-away errors"],
      },
      {
        name: "Labor Planning Agent",
        what: "Forecasts labor needs and optimizes scheduling to match workload.",
        how: "Predicts daily/weekly workload from order forecasts and inbound deliveries, calculates labor hours needed, generates optimal schedules.",
        features: ["Workload forecasting", "Automated schedule generation", "Skill-based assignment", "Overtime prediction", "Temp labor recommendations", "Productivity analytics"],
        painPoints: ["Right-size staff to workload", "Reduce overtime costs", "Never be caught short"],
        metrics: ["30% reduction in overtime", "95% schedule accuracy", "20% improvement in labor productivity"],
      },
    ],
    challenge: [
      { problem: "Route planning is manual and inefficient", impact: "Excess fuel, labor, late deliveries" },
      { problem: "Inventory levels set by gut, not data", impact: "Stockouts and overstocking both costly" },
      { problem: "Perishables expire before selling", impact: "Shrink rates of 5-15% in fresh categories" },
      { problem: "No visibility into delivery status", impact: "Customer complaints, driver hunting" },
      { problem: "Demand spikes catch you off guard", impact: "Stockouts, expedited shipping costs" },
      { problem: "Warehouse labor scheduling is reactive", impact: "Overtime costs, missed SLAs" },
    ],
    integrations: {
      wms: ["Inventory locations and levels", "Pick/pack/ship execution", "Receiving and put-away"],
      tms: ["Route planning", "Driver and vehicle management", "Proof of delivery"],
      erp: ["Purchase orders", "Sales orders", "Inventory transactions"],
    },
    recommendedFirst: "Route Optimization Agent or Expiration/FIFO Agent",
    recommendedWhy: "Immediate cost savings (fuel, labor) or significant shrink reduction for perishables.",
    deploymentTime: "3-4 weeks",
    roi: [
      { metric: "Fuel cost", before: "$200K", after: "$160K", impact: "$40K savings" },
      { metric: "Route planning labor", before: "20 hrs/wk", after: "5 hrs/wk", impact: "$30K savings" },
      { metric: "Perishable shrink", before: "8%", after: "4%", impact: "$40K savings" },
      { metric: "Stockout rate", before: "5%", after: "2%", impact: "$30K recovered" },
      { metric: "Overtime", before: "$80K", after: "$55K", impact: "$25K savings" },
    ],
    faq: [
      { q: "Do I need a TMS to use Route Optimization?", a: "No. The agent can work standalone or integrate with existing TMS systems." },
      { q: "How does this work with my current WMS?", a: "We integrate via API with most WMS platforms. For systems without APIs, we can work with flat file exports/imports." },
      { q: "What about multi-location distribution?", a: "Fully supported. Agents can optimize across multiple warehouses, including transfer recommendations." },
      { q: "Can this handle temperature-controlled routing?", a: "Yes. The agent considers vehicle type and product requirements when building routes." },
    ],
  },
  {
    slug: "customer-service",
    title: "Customer Service",
    shortTitle: "Service",
    description:
      "Delight customers with instant answers while reducing support burden.",
    tagline: "Delight Customers, Without Burning Out Your Team",
    agentCount: 5,
    color: "cyan",
    icon: "chat-bubble",
    keyOutcomes: [
      "85% inquiries resolved without human",
      "70% call volume reduction",
      "Faster resolution times",
    ],
    agents: [
      {
        name: "Product Availability Agent",
        what: "Provides instant, accurate product availability and substitution suggestions.",
        how: "Checks real-time inventory across all locations, responds with availability and timeline, offers substitutions and back-in-stock notifications.",
        features: ["Real-time inventory lookup", "Multi-location availability", "Intelligent substitution suggestions", "Back-in-stock notifications", "Add-to-order capability", "Allergen and dietary info"],
        painPoints: ["Instant availability answers 24/7", "Turn inquiries into orders", "Reduce frustration from stockouts"],
        metrics: ["95% availability inquiries resolved instantly", "30% inquiries converted to orders", "80% reduction in staff time"],
      },
      {
        name: "Order Status Agent",
        what: "Provides comprehensive order status and delivery tracking across all channels.",
        how: "Identifies customer and order, retrieves real-time status from all systems, provides specific response with tracking and POD.",
        features: ["Unified status across systems", "Proactive delay notifications", "Tracking link generation", "POD retrieval", "Issue detection and escalation", "Historical order access"],
        painPoints: ["Eliminate repetitive status calls", "Instant, accurate answers", "Staff freed for higher-value work"],
        metrics: ["85% status inquiries handled without human", "70% reduction in status calls", "Customer satisfaction improvement"],
      },
      {
        name: "Complaint Resolution Agent",
        what: "Handles customer complaints professionally, resolves issues quickly, and learns from patterns.",
        how: "Documents complaint, gathers details and photos, assesses against policy, takes action within authority, escalates complex issues with full context.",
        features: ["Multi-channel complaint intake", "Photo/documentation collection", "Policy-based resolution", "Automated credit/refund processing", "Follow-up confirmation", "Complaint pattern analysis"],
        painPoints: ["Fast, consistent complaint handling", "Customers feel heard immediately", "Identify systemic issues"],
        metrics: ["60% complaints resolved without human", "50% reduction in resolution time", "NPS improvement"],
      },
      {
        name: "Returns & Credits Agent",
        what: "Processes return requests and issues credits quickly and accurately.",
        how: "Validates return request, determines appropriate action, generates RMA and credit memo, coordinates pickup, confirms credit.",
        features: ["Automated eligibility checking", "Policy-based approval", "RMA generation", "Credit memo creation", "Pickup scheduling", "Abuse detection"],
        painPoints: ["Credits in minutes, not days", "Consistent policy application", "Full documentation"],
        metrics: ["70% returns processed automatically", "80% reduction in processing time", "99% credit accuracy"],
      },
      {
        name: "Customer Communication Agent",
        what: "Proactively communicates with customers about orders, issues, and opportunities.",
        how: "Monitors customer-affecting events, sends communications via preferred channel, personalizes based on history, handles responses.",
        features: ["Event-triggered communications", "Channel preference management", "Personalization engine", "Opt-in/opt-out management", "A/B testing of messages", "Engagement tracking"],
        painPoints: ["Customers informed proactively", "Reduce inbound inquiries", "Build trust through transparency"],
        metrics: ["40% reduction in inbound inquiries", "95%+ delivery rate", "Improved satisfaction scores"],
      },
    ],
    challenge: [
      { problem: "High volume of routine inquiries", impact: "Staff overwhelmed, slow response times" },
      { problem: "'Where's my order?' calls dominate", impact: "Low-value work consuming high-value time" },
      { problem: "Complaints handled inconsistently", impact: "Customer churn, negative reviews" },
      { problem: "Returns/credits take too long", impact: "Customer frustration, repeat calls" },
      { problem: "Product questions require research", impact: "Long hold times" },
      { problem: "After-hours support non-existent", impact: "Customers go to competitors" },
    ],
    integrations: {
      communication: ["Phone (Twilio, RingCentral)", "SMS/WhatsApp", "Email (Zendesk, Freshdesk)", "Chat (Intercom, Drift)"],
      backend: ["ERP (order data)", "WMS (inventory, shipment)", "TMS (delivery tracking)", "CRM (customer history)"],
    },
    recommendedFirst: "Order Status Agent or Product Availability Agent",
    recommendedWhy: "High volume, low complexity = immediate impact. Directly reduces call volume.",
    deploymentTime: "2-3 weeks",
    roi: [
      { metric: "Calls handled per day", before: "150", after: "45", impact: "70% reduction" },
      { metric: "CS FTEs needed", before: "4", after: "2", impact: "$100K+ savings" },
      { metric: "Average response time", before: "4 hours", after: "30 seconds", impact: "Customer satisfaction" },
      { metric: "After-hours coverage", before: "None", after: "24/7", impact: "Competitive advantage" },
      { metric: "Complaint resolution time", before: "3 days", after: "4 hours", impact: "Reduced escalations" },
    ],
    faq: [
      { q: "Will customers know they're talking to an AI?", a: "You can configure disclosure. Many customers prefer the speed for routine matters." },
      { q: "What if the agent can't resolve the issue?", a: "Seamless escalation to humans with full context. The customer never has to repeat themselves." },
      { q: "Can the agent access customer history?", a: "Yes, with CRM integration. The agent knows purchase history, past issues, and preferences." },
      { q: "How do you handle angry customers?", a: "Sentiment detection identifies frustrated customers. The agent can de-escalate or transfer to a human specialist." },
    ],
  },
  {
    slug: "finance-ar",
    title: "Finance",
    shortTitle: "Finance",
    description:
      "Get paid faster, collect more, and automate financial operations.",
    tagline: "Get Paid Faster, Collect More, Work Less",
    agentCount: 6,
    color: "green",
    icon: "banknotes",
    keyOutcomes: [
      "10-15 day DSO reduction",
      "85% payment auto-application",
      "60% deduction recovery",
    ],
    agents: [
      {
        name: "Collections Agent",
        what: "Systematically manages the entire collections process from friendly reminders to escalation.",
        how: "Monitors all receivables, segments customers by risk, executes collection campaigns, negotiates payment plans, tracks promises to pay, escalates as needed.",
        features: ["Risk-based prioritization", "Multi-channel outreach", "Configurable escalation sequences", "Payment plan negotiation", "Promise-to-pay tracking", "Automated payment links"],
        painPoints: ["Every customer gets appropriate follow-up", "Consistent, professional process", "Collect more without more staff"],
        metrics: ["10-15 day reduction in DSO", "25% improvement in 60+ day collection", "50% reduction in bad debt write-offs"],
      },
      {
        name: "Credit Management Agent",
        what: "Automates credit decisions for new and existing customers.",
        how: "Pulls business credit reports, bank and trade references, applies scoring model, recommends limit and terms, monitors existing customers for changes.",
        features: ["Digital credit application", "Automated credit pulls", "Reference checking", "Risk scoring model", "Auto-decisioning", "Watch list monitoring"],
        painPoints: ["Credit decisions in minutes, not days", "Consistent policy application", "Early warning on deteriorating accounts"],
        metrics: ["90% of credit decisions automated", "2-hour average decision time", "30% reduction in bad debt"],
      },
      {
        name: "Invoice Dispute Agent",
        what: "Manages customer invoice disputes from intake through resolution.",
        how: "Receives dispute, documents claim, researches automatically (orders, delivery, pricing), determines validity, resolves or escalates with full package.",
        features: ["Multi-channel dispute intake", "Automated research", "Policy-based resolution", "Credit/adjustment processing", "Root cause reporting", "Escalation with full context"],
        painPoints: ["Resolve disputes in hours, not weeks", "Reduce staff research time", "Identify dispute patterns"],
        metrics: ["65% disputes resolved without human", "75% reduction in resolution time", "20% reduction in disputed dollars"],
      },
      {
        name: "Payment Application Agent",
        what: "Automatically matches incoming payments to open invoices.",
        how: "Receives payment information from all sources, parses remittance, matches to invoices, posts to ERP, flags exceptions, sends confirmations.",
        features: ["Multi-format remittance parsing", "Intelligent matching algorithms", "Partial payment allocation", "Deduction identification", "ERP posting automation", "Reconciliation reporting"],
        painPoints: ["Eliminate manual cash application", "Faster posting = better AR visibility", "Identify deductions immediately"],
        metrics: ["85% of payments auto-applied", "70% reduction in cash application time", "Same-day posting"],
      },
      {
        name: "Deduction Management Agent",
        what: "Identifies, categorizes, and resolves customer deductions.",
        how: "Identifies deductions from payment application, categorizes by type, researches validity, approves valid deductions, challenges invalid ones.",
        features: ["Automatic deduction identification", "Categorization engine", "Promotion/deal matching", "Validity research", "Challenge letter generation", "Customer deduction scorecards"],
        painPoints: ["Stop unauthorized deductions", "Recover invalid deductions", "Understand deduction drivers"],
        metrics: ["40% deductions validated/challenged automatically", "60% recovery on challenged deductions", "Full deduction visibility"],
      },
      {
        name: "Financial Reporting Agent",
        what: "Generates AR reports, forecasts cash flow, and provides financial insights.",
        how: "Aggregates AR data, generates standard and custom reports, forecasts cash receipts, alerts on thresholds, provides natural language insights.",
        features: ["Standard AR report library", "Custom report builder", "Cash flow forecasting", "DSO analytics", "Customer health scoring", "Threshold alerting"],
        painPoints: ["Reports ready when needed", "Forecasting for cash planning", "Visibility into AR health"],
        metrics: ["Real-time AR visibility", "90%+ cash forecast accuracy", "Reduced reporting burden"],
      },
    ],
    challenge: [
      { problem: "AR aging keeps climbing", impact: "Cash tied up, borrowing costs increase" },
      { problem: "Collections is manual and inconsistent", impact: "Some customers never get called" },
      { problem: "Invoice disputes drag on for weeks", impact: "Delayed payment, staff time wasted" },
      { problem: "Deductions taken without authorization", impact: "Revenue leakage" },
      { problem: "New customer credit decisions take days", impact: "Delayed first orders, lost business" },
      { problem: "Cash application is manual nightmare", impact: "Staff time, posting errors" },
    ],
    integrations: {
      erp: ["AR subledger", "Customer master", "Invoice data", "Payment posting"],
      banking: ["Bank feeds", "ACH origination", "Lockbox files"],
      credit: ["D&B", "Experian Business", "Equifax Business"],
      communication: ["Email (collection notices)", "SMS (payment reminders)", "Phone (outbound calls)"],
    },
    recommendedFirst: "Collections Agent or Payment Application Agent",
    recommendedWhy: "Direct cash flow impact and measurable DSO improvement, or immediate labor savings.",
    deploymentTime: "3-4 weeks",
    performancePricing: true,
    roi: [
      { metric: "DSO", before: "42 days", after: "32 days", impact: "$274K freed cash (on $10M AR)" },
      { metric: "Collection FTEs", before: "2", after: "0.5", impact: "$75K+ savings" },
      { metric: "Bad debt write-off", before: "1.5%", after: "0.8%", impact: "$70K savings" },
      { metric: "Cash application FTEs", before: "1", after: "0.25", impact: "$37K savings" },
      { metric: "Deduction recovery", before: "30%", after: "65%", impact: "$50K+ recovered" },
    ],
    faq: [
      { q: "Will aggressive collections damage customer relationships?", a: "You control the tone and timing. Our agents are professional and configurable from gentle to firm." },
      { q: "What if a customer claims they never received an invoice?", a: "The agent automatically resends invoice and proof of delivery. This is one of the most common and resolvable disputes." },
      { q: "Can this connect to our bank for payments?", a: "Yes. We integrate with major banks for lockbox files, ACH, and payment data." },
      { q: "How do you handle partial payments?", a: "Configurable allocation rules (oldest first, largest first, specific invoice, etc.)." },
    ],
  },
  {
    slug: "compliance",
    title: "Compliance",
    shortTitle: "Compliance",
    description:
      "Stay compliant without the paperwork nightmare.",
    tagline: "Stay Compliant Without the Paperwork Nightmare",
    agentCount: 5,
    color: "red",
    icon: "shield-check",
    keyOutcomes: [
      "100% traceability",
      "90% faster recall execution",
      "80% reduction in audit prep",
    ],
    agents: [
      {
        name: "Traceability Agent",
        what: "Maintains complete lot-level traceability from supplier through customer delivery.",
        how: "Captures inbound lot info, tracks warehouse movement, records customer allocation, maintains chain of custody, enables instant trace queries.",
        features: ["Lot/batch/serial tracking", "Receiving documentation capture", "Warehouse location tracking", "Trace-forward queries", "Trace-back queries", "FSMA 204 compliance reports"],
        painPoints: ["One-click traceability for any product", "FSMA 204 compliance without manual records", "Instant customer traceability requests"],
        metrics: ["100% lot-level traceability", "Trace queries in seconds", "Full FSMA 204 compliance"],
      },
      {
        name: "Recall Management Agent",
        what: "Enables rapid, accurate recall execution when product issues are identified.",
        how: "Instantly identifies affected lots, customers, and orders; executes notification campaign; tracks acknowledgment; manages returns; documents everything.",
        features: ["Instant affected product identification", "Multi-channel notification", "Acknowledgment tracking", "Return coordination", "Inventory quarantine", "Mock recall capability"],
        painPoints: ["Recall in hours, not days", "100% customer notification", "Complete documentation for regulators"],
        metrics: ["90%+ reduction in recall execution time", "100% notification rate", "Complete audit trail"],
      },
      {
        name: "Document Management Agent",
        what: "Organizes, retrieves, and distributes compliance documents.",
        how: "Ingests supplier documents (COAs, spec sheets, certifications), indexes and links to products, retrieves instantly, tracks expiring certifications.",
        features: ["Document ingestion (PDF, email, portal)", "OCR and data extraction", "Product/lot linking", "Instant search and retrieval", "Automatic distribution rules", "Expiration tracking"],
        painPoints: ["Find any document in seconds", "Automatic customer document delivery", "Never miss expiring certification"],
        metrics: ["95% reduction in document search time", "100% certifications tracked", "Automatic compliance package delivery"],
      },
      {
        name: "Temperature Monitoring Agent",
        what: "Monitors cold chain temperatures and maintains compliance records automatically.",
        how: "Integrates with warehouse and truck sensors, continuously logs temperatures, detects excursions, alerts personnel, documents corrective actions.",
        features: ["Real-time temperature monitoring", "Multi-zone warehouse coverage", "Delivery vehicle integration", "Excursion alerting", "HACCP report generation", "Calibration tracking"],
        painPoints: ["Continuous monitoring without manual checks", "Instant excursion response", "Audit-ready temperature records"],
        metrics: ["100% temperature record coverage", "Real-time excursion alerting", "Zero audit findings on temperature"],
      },
      {
        name: "Audit Preparation Agent",
        what: "Maintains audit readiness and streamlines audit execution.",
        how: "Continuously validates compliance status, identifies gaps, generates pre-audit checklists, assembles audit packages, tracks corrective actions.",
        features: ["Compliance dashboard", "Gap identification", "Pre-audit self-assessment", "Audit package generation", "Corrective action management", "Multi-framework support (FSMA, SQF, BRC)"],
        painPoints: ["Always audit-ready, no scramble", "Identify and fix gaps proactively", "Faster, smoother audits"],
        metrics: ["80% reduction in audit prep time", "50% fewer audit findings", "100% corrective action tracking"],
      },
    ],
    challenge: [
      { problem: "FSMA traceability requirements expanding", impact: "New compliance burden, fines" },
      { problem: "Manual record-keeping for audits", impact: "Staff time, errors, missing docs" },
      { problem: "Recall response is slow and manual", impact: "Liability exposure, safety risk" },
      { problem: "Temperature logging is paper-based", impact: "Gaps in records, audit failures" },
      { problem: "COAs and spec sheets scattered", impact: "Hours to fulfill customer requests" },
      { problem: "Audit prep consumes weeks", impact: "Business disruption, stress" },
    ],
    integrations: {
      wms: ["Receiving events", "Inventory movements", "Lot/batch data", "Pick/pack/ship"],
      hardware: ["Warehouse sensors (Emerson, Dickson)", "Trailer sensors (Carrier, Thermo King)", "Handheld probes"],
      supplier: ["Document retrieval", "Lot information", "Certification data"],
      erp: ["Purchase orders", "Sales orders", "Customer master"],
    },
    recommendedFirst: "Traceability Agent or Document Management Agent",
    recommendedWhy: "FSMA 204 deadline compliance or quick win with immediate time savings.",
    deploymentTime: "4-6 weeks",
    roi: [
      { metric: "Time to trace query", before: "4 hours", after: "5 minutes", impact: "Compliance, satisfaction" },
      { metric: "Audit prep time", before: "2 weeks", after: "2 days", impact: "Staff productivity" },
      { metric: "Recall notification time", before: "24-48 hours", after: "2 hours", impact: "Safety, liability" },
      { metric: "Document retrieval time", before: "30 minutes", after: "30 seconds", impact: "Staff time saved" },
      { metric: "Compliance staff needed", before: "2 FTEs", after: "0.5 FTE", impact: "$75K+ savings" },
    ],
    faq: [
      { q: "When does FSMA 204 take effect?", a: "January 20, 2026 for most operations. Enhanced traceability requirements apply to foods on the Food Traceability List." },
      { q: "Do I need to replace my current lot tracking?", a: "No. DistroAgents can work with your existing system, enhancing it with additional capabilities and reporting." },
      { q: "What about products not on the Food Traceability List?", a: "Even if not required, traceability is good practice and increasingly expected by customers." },
      { q: "Can customers access their own compliance documents?", a: "Yes. Customer portal option allows self-service access to COAs, spec sheets, and traceability reports." },
    ],
  },
];

export const colorMap: Record<string, { bg: string; text: string; border: string; accent: string }> = {
  blue: { bg: "bg-blue-500/10", text: "text-blue-400", border: "border-blue-500/20", accent: "#3b82f6" },
  green: { bg: "bg-green-500/10", text: "text-green-400", border: "border-green-500/20", accent: "#22c55e" },
  purple: { bg: "bg-purple-500/10", text: "text-purple-400", border: "border-purple-500/20", accent: "#a855f7" },
  orange: { bg: "bg-orange-500/10", text: "text-orange-400", border: "border-orange-500/20", accent: "#f97316" },
  cyan: { bg: "bg-cyan-500/10", text: "text-cyan-400", border: "border-cyan-500/20", accent: "#06b6d4" },
  red: { bg: "bg-red-500/10", text: "text-red-400", border: "border-red-500/20", accent: "#ef4444" },
};
